dc_corr:
  noiseless_meas_available: false
  scale_relative: false
  step: 0.2
  use: true
degr_update_method:
  type: look_back
dt: 0.02
model_ckpt: checkpoints/deblur_imagenet_dt_1.0.ckpt
stop_t: 0.0
x0_pred_in_last_step: true