dc_corr:
  noiseless_meas_available: false
  scale_relative: true
  step: 0.0
  use: false
degr_update_method:
  type: look_ahead
dt: 0.01
model_ckpt: checkpoints/inpaint_imagenet_dt_0.0.ckpt
stop_t: 0.0
x0_pred_in_last_step: false