base:
  img_resolution: 256                 
  in_channels: 3                     
  out_channels: 3                     
  label_dim: 0            
  augment_dim: 0            
  model_channels: 128          
  channel_mult: [1, 1, 2, 2, 2, 2, 2]    
  channel_mult_emb: 4            
  num_blocks: 2            
  attn_resolutions: [16]        
  dropout: 0.10         
  label_dropout: 0            
  embedding_type: fourier   
  channel_mult_noise: 2            
  encoder_type: residual   
  decoder_type: standard  
  resample_filter: [1,3,3,1]
large:
  img_resolution: 256                 
  in_channels: 3                     
  out_channels: 3                     
  label_dim: 0            
  augment_dim: 0            
  model_channels: 256          
  channel_mult: [1, 1, 2, 2, 4, 4]    
  channel_mult_emb: 4            
  num_blocks: 2            
  attn_resolutions: [32, 16, 8]     
  dropout: 0.0         
  label_dropout: 0            
  embedding_type: fourier   
  channel_mult_noise: 2            
  encoder_type: residual   
  decoder_type: standard  
  resample_filter: [1,3,3,1]